  default:
    app:
      hostName: localhost
      hostURL: 
      env: local
      title: RDOM
      port: 5000
      version: 1.0
      timezone: America/Los_Angeles
      timezoneOffset: +0:00
      cookieKey: 'RSSCOOKIEKEY'

    web:
      url: "http://localhost:4200" 
  
    secret:
      key: "keepItSecretWithRoadSmartSolutionAban@@!@#"
      expiresIn: "900h"
      username: "Dev"
      password: "rssapiaban@@@#1"
    
    db:
      development: "mongodb+srv://nftthee:nftthee@cluster0.hov9i7k.mongodb.net/"



  